#!/bin/bash
# =============================================================================
#  eval-gate: block until the Mindwell training jobs finish, then verify SUCCESS.
# =============================================================================
#  Used by run_full_pipeline.sh to bridge the train→eval cross-cluster gap
#  WITHOUT a cross-cluster afterok (VSC doesn't support those) and WITHOUT
#  holding a GPU while waiting: this runs as a cheap 1-CPU job on wICE, and the
#  eval GPU arrays `afterok`-depend on it, so they stay PENDING until release.
#
#  Post-mortem hardening (2026-07-04 run): the previous gate released on queue
#  COMPLETION alone — all 64 training tasks had FAILED, yet eval was released
#  against an empty trained-model manifest, and the gate log contained just two
#  lines for a 4.7-hour watch. This version:
#    * logs EVERY poll (timestamp + raw remaining-count) so any misfire is
#      diagnosable after the fact;
#    * requires 2 CONSECUTIVE empty-queue polls (guards transient empty reads);
#    * after the queue drains, checks the per-track SUCCESS sentinels that
#      train_{pd,lgd}.slurm write only when a trial actually SAVED — and
#      says loudly whether eval is being released onto real checkpoints or
#      onto a baselines-only roster.
#  It still always exits 0 (eval's skip-existing logic is safe either way and
#  the timeout is the backstop) — but the log now tells the whole story.
#
#  As of 2026-07-08 it also SUBMITS the eval arrays once training finishes (arg
#  3 = a generated eval-submit script) — so eval is never queued on the GPUs
#  while training runs, and is only submitted for tracks that actually saved a
#  checkpoint (the script self-checks the train_ok_<track> sentinels).
#
#  Usage:  _wait_for_jobs.sh <comma-separated-mindwell-jobids> [max_polls] [eval_submit_script]
#  Env:    CREDITPFN_OUTPUT_ROOT (for the .sentinels dir; default $VSC_DATA/CreditPFN)
# =============================================================================
set -uo pipefail

JIDS="${1:?usage: _wait_for_jobs.sh <comma-separated-jobids> [max_polls] [eval_submit_script]}"
MAX="${2:-2400}"                       # polls × 30s  (2400 = 20 h)
EVAL_SCRIPT="${3:-}"                    # generated by run_full_pipeline.sh
OUT="${CREDITPFN_OUTPUT_ROOT:-${VSC_DATA}/CreditPFN}"
SENT_DIR="${OUT}/.sentinels"

echo "$(date '+%F %T') eval-gate: watching Mindwell train jobs [${JIDS}] (max $((MAX * 30 / 3600)) h, poll=30s)"
echo "$(date '+%F %T') eval-gate: success sentinels expected under ${SENT_DIR}/train_ok_{pd,lgd}"

consecutive_empty=0
for i in $(seq 1 "${MAX}"); do
    out=$(squeue -M mindwell -h -o "%i %T" -j "${JIDS}" 2>&1)
    rc=$?
    if [ ${rc} -eq 0 ]; then
        remaining=$(printf '%s\n' "${out}" | grep -cE '^[0-9]' || true)
        echo "$(date '+%F %T') eval-gate: poll ${i}  remaining=${remaining}  [$(printf '%s' "${out}" | grep -E '^[0-9]' | tr '\n' ';' | cut -c1-160)]"
        if [ "${remaining}" -eq 0 ]; then
            consecutive_empty=$((consecutive_empty + 1))
            if [ "${consecutive_empty}" -ge 2 ]; then
                echo "$(date '+%F %T') eval-gate: queue drained (2 consecutive empty polls) after $((i * 30)) s."
                break
            fi
        else
            consecutive_empty=0
        fi
    else
        # A FAILED query must never count as completion — keep waiting.
        echo "$(date '+%F %T') eval-gate: poll ${i}  squeue FAILED (rc=${rc}): $(printf '%s' "${out}" | head -c 200)"
        consecutive_empty=0
    fi
    sleep 30
done

# --- archive fallback checkpoints into PROJECT STAGING ------------------------
# Trained checkpoints belong on project storage (persistent, big-file tier).
# When staging is NOT writable from the Mindwell compute nodes (the Jul-3
# failure mode), resolve_writable_staging_path falls back to $VSC_DATA — so
# this gate, which runs on wICE (Lustre-writable, proven by the data job),
# COPIES any fallback checkpoints into staging before releasing eval. Copy,
# not move: the training manifest records the $VSC_DATA paths and eval reads
# them from there; the staging copy is the durable archive. Reclaim the
# $VSC_DATA space later with scripts/clean_run.py once staging is verified.
STAGING_BASE="${CREDITPFN_STAGING_ROOT:-${TABPFN_STAGING_ROOT:-/lustre1/project/stg_00211}}"
case "${STAGING_BASE}" in
    */CreditPFN) STAGE="${STAGING_BASE}" ;;
    *)           STAGE="${STAGING_BASE}/CreditPFN" ;;
esac
FALLBACK_DIR="${OUT}/checkpoints/trained"
if [ -d "${FALLBACK_DIR}" ] && [ -n "$(find "${FALLBACK_DIR}" -name '*.ckpt' -print -quit 2>/dev/null)" ]; then
    n_ckpt=$(find "${FALLBACK_DIR}" -name '*.ckpt' | wc -l)
    echo "$(date '+%F %T') eval-gate: ${n_ckpt} checkpoint(s) found in the \$VSC_DATA fallback dir — archiving to staging ${STAGE}/checkpoints/trained/"
    if mkdir -p "${STAGE}/checkpoints/trained" 2>/dev/null; then
        if command -v rsync >/dev/null 2>&1; then
            rsync -a "${FALLBACK_DIR}/" "${STAGE}/checkpoints/trained/" \
                && echo "$(date '+%F %T') eval-gate: archive to staging OK (rsync)." \
                || echo "$(date '+%F %T') eval-gate: WARNING — rsync to staging failed; checkpoints remain only on \$VSC_DATA."
        else
            cp -rn "${FALLBACK_DIR}/." "${STAGE}/checkpoints/trained/" \
                && echo "$(date '+%F %T') eval-gate: archive to staging OK (cp)." \
                || echo "$(date '+%F %T') eval-gate: WARNING — cp to staging failed; checkpoints remain only on \$VSC_DATA."
        fi
    else
        echo "$(date '+%F %T') eval-gate: WARNING — cannot create ${STAGE}/checkpoints/trained even from wICE; checkpoints remain on \$VSC_DATA only."
    fi
else
    echo "$(date '+%F %T') eval-gate: no fallback checkpoints on \$VSC_DATA (either training wrote staging directly, or nothing saved)."
fi

# --- success verification ----------------------------------------------------
ok_pd=""; ok_lgd=""
[ -f "${SENT_DIR}/train_ok_pd"  ] && ok_pd="yes"
[ -f "${SENT_DIR}/train_ok_lgd" ] && ok_lgd="yes"
echo "$(date '+%F %T') eval-gate: success sentinels — pd=${ok_pd:-NO} lgd=${ok_lgd:-NO}"

if [ -z "${ok_pd}" ] && [ -z "${ok_lgd}" ]; then
    echo "=================================================================="
    echo "WARNING: NO training task on EITHER track reported success."
    echo "         Eval will run against a baselines-only roster (no trained"
    echo "         checkpoints). Check the train_*.log files on \$VSC_DATA"
    echo "         before trusting any downstream comparison."
    echo "=================================================================="
elif [ -z "${ok_pd}" ] || [ -z "${ok_lgd}" ]; then
    echo "WARNING: only ONE track has successful trials (pd=${ok_pd:-NO} lgd=${ok_lgd:-NO})."
fi

# --- submit the eval arrays now that training has finished --------------------
# (Eval is submitted here, POST-training, rather than pre-queued — so no eval
#  GPU job waits in the queue during training. The script self-gates per track
#  on the train_ok_<track> sentinels, so a track that produced no checkpoint
#  submits nothing.)
if [ -n "${EVAL_SCRIPT}" ] && [ -f "${EVAL_SCRIPT}" ]; then
    echo "$(date '+%F %T') eval-gate: training finished — submitting eval via ${EVAL_SCRIPT}"
    bash "${EVAL_SCRIPT}"
    echo "$(date '+%F %T') eval-gate: eval submission done."
else
    echo "$(date '+%F %T') eval-gate: no eval-submit script provided (${EVAL_SCRIPT:-none}) — nothing to submit."
fi
exit 0
