#!/bin/bash
# =============================================================================
#  eval-gate: block until the Mindwell training jobs finish, then verify SUCCESS.
# =============================================================================
#  Used by run_full_pipeline.sh to bridge the train→eval cross-cluster gap
#  WITHOUT a cross-cluster afterok (VSC doesn't support those) and WITHOUT
#  holding a GPU while waiting: this runs as a cheap 1-CPU job on wICE, and the
#  eval GPU arrays `afterok`-depend on it, so they stay PENDING until release.
#
#  Post-mortem hardening (2026-07-04 run): the previous gate released on queue
#  COMPLETION alone — all 64 training tasks had FAILED, yet eval was released
#  against an empty trained-model manifest, and the gate log contained just two
#  lines for a 4.7-hour watch. This version:
#    * logs state changes plus a 10-minute heartbeat (rather than thousands of
#      identical 30-second lines) so any misfire remains diagnosable;
#    * requires 2 CONSECUTIVE empty-queue polls (guards transient empty reads);
#    * after the queue drains, reports PER-TASK success-sentinel counts. The
#      generated submit script requires the full planned count before eval.
#    * treats a watch timeout as failure instead of releasing eval while train
#      tasks may still be running.
#
#  As of 2026-07-08 it also SUBMITS the eval arrays once training finishes (arg
#  3 = a generated eval-submit script) — so eval is never queued on the GPUs
#  while training runs, and is only submitted for tracks whose complete array
#  wrote train_ok_<track>_<index> sentinels.
#
#  Usage:  _wait_for_jobs.sh <comma-separated-mindwell-jobids> [max_polls] [eval_submit_script]
#  Env:    CREDITPFN_OUTPUT_ROOT (for the .sentinels dir; default $VSC_DATA/CreditPFN)
# =============================================================================
set -uo pipefail

JIDS="${1:?usage: _wait_for_jobs.sh <comma-separated-jobids> [max_polls] [eval_submit_script]}"
# polls × 30s. Raised 2400 (20 h) → 8400 (70 h) on 2026-08-06: the first
# two-family run needed 47 h of WALL-CLOCK (7.5 h queued before the first task
# even started, then Mindwell granted only 1–2 concurrent GPUs instead of the
# requested 24), so the gate expired with PD at task 19/47 and LGD not started
# — and eval never ran at all. Sizing this off "how long should it take" was
# the mistake; size it off the job's own walltime instead.
MAX="${2:-8400}"
EVAL_SCRIPT="${3:-}"                    # generated by run_full_pipeline.sh
OUT="${CREDITPFN_OUTPUT_ROOT:-${VSC_DATA}/CreditPFN}"
SENT_DIR="${OUT}/.sentinels"

echo "$(date '+%F %T') eval-gate: watching Mindwell train jobs [${JIDS}] (max $((MAX * 30 / 3600)) h, poll=30s)"
echo "$(date '+%F %T') eval-gate: per-task sentinels expected under ${SENT_DIR}/train_ok_{pd,lgd}_<index>"

consecutive_empty=0
last_remaining=""
drained=0
for i in $(seq 1 "${MAX}"); do
    out=$(squeue -M mindwell -h -o "%i %T" -j "${JIDS}" 2>&1)
    rc=$?
    if [ ${rc} -eq 0 ]; then
        remaining=$(printf '%s\n' "${out}" | grep -cE '^[0-9]' || true)
        if [ "${remaining}" != "${last_remaining}" ] || [ "${i}" -eq 1 ] || [ $((i % 20)) -eq 0 ]; then
            echo "$(date '+%F %T') eval-gate: poll ${i}  remaining=${remaining}  [$(printf '%s' "${out}" | grep -E '^[0-9]' | tr '\n' ';' | cut -c1-160)]"
        fi
        last_remaining="${remaining}"
        if [ "${remaining}" -eq 0 ]; then
            consecutive_empty=$((consecutive_empty + 1))
            if [ "${consecutive_empty}" -ge 2 ]; then
                echo "$(date '+%F %T') eval-gate: queue drained (2 consecutive empty polls) after $((i * 30)) s."
                drained=1
                break
            fi
        else
            consecutive_empty=0
        fi
    else
        # A FAILED query must never count as completion — keep waiting.
        echo "$(date '+%F %T') eval-gate: poll ${i}  squeue FAILED (rc=${rc}): $(printf '%s' "${out}" | head -c 200)"
        consecutive_empty=0
    fi
    sleep 30
done

if [ "${drained}" -ne 1 ]; then
    echo "$(date '+%F %T') eval-gate: ERROR - timed out before the Mindwell queue drained; eval was NOT submitted." >&2
    # Make the recovery a copy-paste, not a re-derivation. The generated
    # submitter computes the roster at execution time, so running it later is
    # exactly equivalent to the gate having fired — it just needs training to
    # have finished first. (2026-08-06: the previous timeout left the user with
    # no instructions and a completed 47 h training run that was never scored.)
    echo "" >&2
    echo "  RECOVER: wait for the Mindwell array to finish, then run ON A LOGIN NODE:" >&2
    if [ -n "${EVAL_SCRIPT}" ]; then
        echo "      bash '${EVAL_SCRIPT}'" >&2
    else
        echo "      STAGES=\"eval\" bash scripts/slurm/run_full_pipeline.sh" >&2
    fi
    echo "  Check first:  squeue -M mindwell -j '${JIDS}'   (must be empty)" >&2
    echo "  Sentinels  :  ls '${SENT_DIR}'/train_ok_* | wc -l" >&2
    exit 1
fi

# --- archive fallback checkpoints into PROJECT STAGING ------------------------
# Trained checkpoints belong on project storage (persistent, big-file tier).
# When staging is NOT writable from the Mindwell compute nodes (the Jul-3
# failure mode), resolve_writable_staging_path falls back to $VSC_DATA — so
# this gate, which runs on wICE (Lustre-writable, proven by the data job),
# COPIES any fallback checkpoints into staging before releasing eval. Copy,
# not move: the training manifest records the $VSC_DATA paths and eval reads
# them from there; the staging copy is the durable archive. Reclaim the
# $VSC_DATA space later with python -m src.utils.clean_run once staging is verified.
STAGING_BASE="${CREDITPFN_STAGING_ROOT:-${TABPFN_STAGING_ROOT:-/lustre1/project/stg_00211}}"
case "${STAGING_BASE}" in
    */CreditPFN) STAGE="${STAGING_BASE}" ;;
    *)           STAGE="${STAGING_BASE}/CreditPFN" ;;
esac
FALLBACK_DIR="${OUT}/checkpoints/trained"
if [ -d "${FALLBACK_DIR}" ] && [ -n "$(find "${FALLBACK_DIR}" -name '*.ckpt' ! -name '*.epoch_eval.ckpt' -print -quit 2>/dev/null)" ]; then
    n_ckpt=$(find "${FALLBACK_DIR}" -name '*.ckpt' ! -name '*.epoch_eval.ckpt' | wc -l)
    echo "$(date '+%F %T') eval-gate: ${n_ckpt} checkpoint(s) found in the \$VSC_DATA fallback dir — archiving to staging ${STAGE}/checkpoints/trained/"
    if mkdir -p "${STAGE}/checkpoints/trained" 2>/dev/null; then
        if command -v rsync >/dev/null 2>&1; then
            rsync -a --exclude='*.epoch_eval.ckpt' "${FALLBACK_DIR}/" "${STAGE}/checkpoints/trained/" \
                && echo "$(date '+%F %T') eval-gate: archive to staging OK (rsync)." \
                || echo "$(date '+%F %T') eval-gate: WARNING — rsync to staging failed; checkpoints remain only on \$VSC_DATA."
        else
            copy_rc=0
            while IFS= read -r -d '' src; do
                rel="${src#${FALLBACK_DIR}/}"
                dst="${STAGE}/checkpoints/trained/${rel}"
                mkdir -p "$(dirname "${dst}")" && cp -n "${src}" "${dst}" || copy_rc=1
            done < <(find "${FALLBACK_DIR}" -type f \( \( -name '*.ckpt' ! -name '*.epoch_eval.ckpt' \) -o -name '*.ckpt.provenance.json' \) -print0)
            if [ "${copy_rc}" -eq 0 ]; then
                echo "$(date '+%F %T') eval-gate: archive to staging OK (cp)."
            else
                echo "$(date '+%F %T') eval-gate: WARNING - cp to staging failed; checkpoints remain only on \$VSC_DATA."
            fi
        fi
    else
        echo "$(date '+%F %T') eval-gate: WARNING — cannot create ${STAGE}/checkpoints/trained even from wICE; checkpoints remain on \$VSC_DATA only."
    fi
else
    echo "$(date '+%F %T') eval-gate: no fallback checkpoints on \$VSC_DATA (either training wrote staging directly, or nothing saved)."
fi

# --- success verification ----------------------------------------------------
n_ok_pd=$(find "${SENT_DIR}" -maxdepth 1 -type f -name 'train_ok_pd_*' 2>/dev/null | wc -l)
n_ok_lgd=$(find "${SENT_DIR}" -maxdepth 1 -type f -name 'train_ok_lgd_*' 2>/dev/null | wc -l)
echo "$(date '+%F %T') eval-gate: successful array tasks - pd=${n_ok_pd} lgd=${n_ok_lgd}"

if [ "${n_ok_pd}" -eq 0 ] && [ "${n_ok_lgd}" -eq 0 ]; then
    echo "=================================================================="
    echo "WARNING: NO training task on EITHER track reported success."
    echo "         Eval will not be submitted for an incomplete track."
    echo "=================================================================="
elif [ "${n_ok_pd}" -eq 0 ] || [ "${n_ok_lgd}" -eq 0 ]; then
    echo "WARNING: only one track has successful tasks (pd=${n_ok_pd} lgd=${n_ok_lgd})."
fi

# --- submit the eval arrays now that training has finished --------------------
# (Eval is submitted here, POST-training, rather than pre-queued — so no eval
#  GPU job waits in the queue during training. The generated script self-gates
#  per track on the full per-task sentinel count, so a partial grid submits
#  nothing.)
if [ -n "${EVAL_SCRIPT}" ] && [ -f "${EVAL_SCRIPT}" ]; then
    echo "$(date '+%F %T') eval-gate: training finished — submitting eval via ${EVAL_SCRIPT}"
    if bash "${EVAL_SCRIPT}"; then
        echo "$(date '+%F %T') eval-gate: eval submission done."
    else
        rc=$?
        echo "$(date '+%F %T') eval-gate: ERROR - eval submission script failed (rc=${rc})." >&2
        exit "${rc}"
    fi
else
    echo "$(date '+%F %T') eval-gate: no eval-submit script provided (${EVAL_SCRIPT:-none}) — nothing to submit."
fi
exit 0
